version: '3.1'
services:
  book-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql@14/data/
    ports:
      - 5432:5432
  adminer:
    depends_on: 
      - book-db
    image: adminer
    restart: always
    ports:
      - 8090:8080
  smtp:
    image: ixdotai/smtp:latest
    ports:
      - 127.0.0.1:25:25
      - 2525:2525
      - 587:587
    environment:
      - SMARTHOST_ADDRESS=smtp.sendgrid.net
      - SMARTHOST_PORT=587
      - SMARTHOST_USER=apikey
      - SMARTHOST_PASSWORD=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
      - SMARTHOST_ALIASES=*.sendgrid.net
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025