version: '3.1'
services:
  book-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  adminer:
    depends_on: 
      - book-db
    image: adminer
    restart: always
    ports:
      - 8090:8080
  smtp:
    image: ixdotai/smtp:latest
    ports:
      - 127.0.0.1:25:25
    environment:
      - SMARTHOST_ADDRESS=smtp.sendgrid.net
      - SMARTHOST_PORT=587
      - SMARTHOST_USER=apikey
      - SMARTHOST_PASSWORD=SG.blahblahblahblahWoSpQodvLakqXQfxo
      - SMARTHOST_ALIASES=*.sendgrid.net